// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"VsConvertEscapeCharacters","status":true,"description":"Version 1.2.0 allows custom escape characters in message boxes","parameters":{}},
{"name":"VsUtils","status":true,"description":"Version 1.5.0 VsUtils, helper methods and other utilities","parameters":{}},
{"name":"VsAnimations","status":true,"description":"","parameters":{}},
{"name":"demo","status":true,"description":"","parameters":{}}
];
